### ISSUE TITLE
Change flags

### ISSUE THREAD

**Issue by talos** [GovLab/OpenData500#128]
Add: South Korea, Italy and Russia

Add: Coming Soon under Australia, South Korea, Italy, and Russia

**Comment by talos** [comment]
Resolved by https://github.com/GovLab/OpenData500/commit/b611c40b38f68f56c6efc7f777ff754d9e79c00b

@rdc112 Can you check out http://opendata500.com/9/ ?

The "Coming Soon" is so dim to be near-invisible.  How do you feel about involving Claudio to put together some kind of badge or sash on the flags to notate they are "coming soon"?

**Comment by rdc112** [comment]
Yeah, that's a good idea, especially because the lorem ipsum's below the
other countries are going to go

**Comment by talos** [comment]
Done.
