### ISSUE TITLE
Other issues

### ISSUE THREAD

**Issue by rdc112** [GovLab/OpenData500#129]
Change "Open Data Network" to "Open Data 500 Network"

Remove Lorem Ipsum's from below countries

Change copy below title to: 

The Open Data 500 Network is the first comprehensive study of companies and NGOs using open data in countries around the world.

**Comment by talos** [comment]
@rdc112 Thanks!  I noticed the missing "500" just after pushing.  Other changes should be live on opendata500.com/9 .
