### ISSUE TITLE
Changes to better manage a 'living' company list on the website

### ISSUE THREAD

**Issue by aa-govlab** [GovLab/OpenData500#35]
Pls could there be a distinction between submitted surveys that are displayed & vetted vs. the ones that have been vetted but for some reason not displayed (or vice versa).

It would be EVEN better to have a distinct section for all those surveys that are not displayed because they have actively been dropped.

Thanks Luis!

**Comment by luisdaniel** [comment]
Closing because super old and I'm leaving : )
